name: GitHub Snake Animasyonu Üret

on:
  schedule:
    - cron: "0 0 * * *"   # her gün gece yarısı otomatik günceller
  workflow_dispatch: {}     # Actions sekmesinden elle de tetikleyebilirsin
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Repoyu indir
        uses: actions/checkout@v4

      - name: Katkı yılanını üret
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yilmazyunusemre
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "output" dalına yayınla
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Yılan animasyonu güncellendi [skip ci]"
